branches:
  only:
    - master
    - develop
    - /release/.*/
    - /hotfix/.*/
    - /feature/.*/

install:
  - choco install gitversion.portable -pre -y
  
image: Visual Studio 2019

assembly_info:
  patch: false

before_build:
  - nuget restore source/Jobbr.ComponentModel.Registration.sln
  - ps: C:\ProgramData\chocolatey\lib\GitVersion.Portable\tools\GitVersion.exe /l console /output buildserver /updateAssemblyInfo

platform: Any CPU
configuration: Release

build:
  parallel: true 
  project: source/Jobbr.ComponentModel.Registration.sln

after_build:
  - cmd: nuget pack source\Jobbr.ComponentModel.Registration.nuspec -version "%GitVersion_SemVer%" -prop "target=%CONFIGURATION%"
  - cmd: appveyor PushArtifact "Jobbr.ComponentModel.Registration.%GitVersion_SemVer%.nupkg"

deploy:
- provider: NuGet
  server: https://nuget.org
  api_key:
    secure: M0g00y28joGDzBurWk8q1R4VNLm5FQF/a81NvbLa+GZ7mNWEHQii5EtFtuZTNnC1
  on:
    appveyor_repo_tag: true