image: Visual Studio 2017

environment:
  nodejs_version: "8"

branches:
  only:
    - master
    - develop
    - /release/.*/
    - /hotfix/.*/
    - /feature/.*/

install:
  - choco install gitversion.portable --version 4.0.0
  - ps: Install-Product node $env:nodejs_version
  - npm install source/Jobbr.Dashboard.Frontend/jobbr-dashboard --prefix source/Jobbr.Dashboard.Frontend/jobbr-dashboard

assembly_info:
  patch: false

before_build:
  - nuget restore source/Jobbr.Dashboard.sln
  - ps: C:\ProgramData\chocolatey\lib\GitVersion.Portable\tools\GitVersion.exe /l console /output buildserver /updateAssemblyInfo

platform: Any CPU
configuration: Release

build:
  parallel: true 
  project: source/Jobbr.Dashboard.sln

test: off

after_build:
  - cmd: cd source\Jobbr.Dashboard.Frontend\jobbr-dashboard & au build --env prod
  - cmd: cd source\Jobbr.Dashboard.Frontend\jobbr-dashboard\dist & 7z a -tzip dashboard-app.zip *.*
  - cmd: cd ..\..\..\..
  - cmd: nuget pack Jobbr.Dashboard.nuspec -version "%GitVersion_SemVer%" -prop "target=%CONFIGURATION%" -Symbols
  - cmd: appveyor PushArtifact "Jobbr.Dashboard.%GitVersion_SemVer%.nupkg"
  - cmd: appveyor PushArtifact "Jobbr.Dashboard.%GitVersion_SemVer%.symbols.nupkg"

deploy:
- provider: NuGet
  server: https://nuget.org
  api_key:
    secure: dmAor9/81YJtHhqccxBN1aHyDgLVB96KSqRlqnaiFxqF5ROMgz3jCivW8ROvv4N3
  on:
    appveyor_repo_tag: true