branches:
  only:
    - master
    - develop
    - /release/.*/
    - /hotfix/.*/
    - /feature/.*/

install:
  - git submodule update --init --recursive
  - choco install gitversion.portable -pre -y

assembly_info:
  patch: false

before_build:
  - nuget restore source/Jobbr.ArtefactStorage.FileSystem.sln
  - ps: C:\ProgramData\chocolatey\lib\GitVersion.Portable\tools\GitVersion.exe /l console /output buildserver /updateAssemblyInfo

platform: Any CPU
configuration: Release

build:
  parallel: true 
  project: source/Jobbr.ArtefactStorage.FileSystem.sln

after_build:
  - cmd: nuget pack source\Jobbr.ArtefactStorage.FileSystem.nuspec -version "%GitVersion_SemVer%" -prop "target=%CONFIGURATION%"
  - cmd: appveyor PushArtifact "Jobbr.ArtefactStorage.FileSystem.%GitVersion_SemVer%.nupkg"

test:
  assemblies:
    - '**\bin\Release\Jobbr.ArtefactStorage.FileSystem.Tests.dll'

deploy:
- provider: NuGet
  server: https://nuget.org
  api_key:
    secure: Ompe3bFsh5jBqgp8qFAIkD8D6H4ddqj1kUlyONQFhL5O7Cfuk1LesnyDb4TU63dd
  on:
    appveyor_repo_tag: true