name: CI

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: environment-${{github.ref}}
  cancel-in-progress: true

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  GITHUBACTIONS: "True"

jobs:
  build:
    name: ${{ matrix.platform.name }} ${{ matrix.dotnet.name }}
    runs-on: ${{ matrix.platform.os }}

    strategy:
      fail-fast: false
      matrix:
        platform:
          - { name: Linux, os: ubuntu-24.04 }
          - { name: Windows, os: windows-2025 }
          - { name: macOS x64, os: macos-13 }
        dotnet:
          - { name: .NET 6, version: "6.0.x" }
          - { name: .NET 7, version: "7.0.x" }
          - { name: .NET 8, version: "8.0.x" }
          - { name: .NET 9, version: "9.0.x" }
          # Deactivate .NET 10 (preview) for now as it causes issues on macOS
          # https://github.com/actions/setup-dotnet/issues/645
          #- { name: .NET 10, version: "10.0.x" }

    steps:
      - name: Check out Jobbr
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup NodeJS 
        uses: actions/setup-node@v4
        with:
          node-version: 10
      - name: Install NPM Dependencies
        working-directory: src/Dashboard.Frontend
        run: |
          npm install
          npm install -g aurelia-cli
      - name: Build Aurelia Application
        working-directory: src/Dashboard.Frontend
        run: au build --env prod
      - name: Package Aurelia Application
        working-directory: src/Dashboard.Frontend/dist
        run: |
          7z a -tzip dashboard-app.zip *.*
          cp dashboard-app.zip ../../../dashboard-app.zip
          cp dashboard-app.zip ../../Dashboard/dashboard-app.zip

      - name: Setup .NET ${{ matrix.dotnet.version }} SDK
        id: setup-dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet.version }}
      - name: Enforce SDK Version
        run: dotnet new globaljson --sdk-version ${{ steps.setup-dotnet.outputs.dotnet-version }} --force
      - name: Verify SDK Installation
        run: dotnet --info
        continue-on-error: true

      - name: Install Jobbr Dependencies
        run: dotnet restore

      - name: Build Jobbr
        run: dotnet build --configuration Release --no-restore

      - name: Install Docker on MacOS
        if: runner.os == 'macOS' && matrix.dotnet.name == '.NET 6'
        run: |
          brew install colima
          brew install docker --formula
          colima start
      - name: Install SQL Server on Linux or MacOS
        if: runner.os != 'Windows' && matrix.dotnet.name == '.NET 6'
        run: docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=1StrongPwd!!" -p 1433:1433 -d mcr.microsoft.com/mssql/server:2019-latest
      - name: Install SQL Server on Windows
        if: runner.os == 'Windows' && matrix.dotnet.name == '.NET 6'
        run: choco install sql-server-2019 -y --params="'/Q /SUPPRESSPRIVACYSTATEMENTNOTICE /IACCEPTSQLSERVERLICENSETERMS /ACTION=Install /SkipRules=RebootRequiredCheck /FEATURES=SQLENGINE /SECURITYMODE=SQL /TCPENABLED=1 /SAPWD=1StrongPwd!!'"

      - name: Test Jobbr
        if: matrix.dotnet.name == '.NET 6'
        run: dotnet test --configuration Release --no-restore --logger GitHubActions

      - name: Pack Jobbr
        run: dotnet pack --configuration Release -o publish --include-symbols -p:SymbolPackageFormat=snupkg

      - name: Upload Jobbr NuGet Packages
        uses: actions/upload-artifact@v4
        with:
          name: jobbr-${{ matrix.platform.os }}-${{ matrix.dotnet.version }}
          path: publish/*nupkg

      - name: Publish Jobbr NuGet Packages
        if: github.ref == 'refs/heads/master' && matrix.dotnet.name == '.NET 6' && runner.os == 'Windows'
        run: |
          foreach($file in (Get-ChildItem publish -Recurse -Include *.nupkg)) {
              dotnet nuget push $file --api-key "${{ secrets.NUGET_APIKEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
          }